name: input demo

on:
  workflow_dispatch:
    inputs:
      Owner:
        description: Owner Name
        type: string
        default: DevOps
      Age:
        description: Age
        type: number
        required: true
      Gender:
        description: Gender
        type: choice
        options:
          - Male
          - Female
      Married:
        description: 'Is married?'
        type: boolean


jobs:
  input:
    runs-on: ubuntu-latest
    steps:
    -  name: taking owner name
       run: echo "Hello ${{ inputs.Owner }}, This is a demo for inputs in github action"
    -  name: taking owner age
       run: echo Owner's age is: ${{ inputs.Age }} 
